### ISSUE TITLE
BOSEAN FS-600: All settings reset to defaults after restart

### ISSUE THREAD

**Issue by kroftjan** [Gissio/radpro#33] opened 2024-03-21 13:22 UTC
No custom settings (units, avg. timer, rate&dose alarm, geiger tube,...) are kept after the device is restarted. Time is kept but not the timezone. 
I have a BOSEAN FS-600 running RadPro version 2.0beta23

Otherwise, the software is absolutely awesome and actually makes the device usable (original firmware readings are mostly nonsense)

**Comment by Dsl71** [comment] 2024-03-21 14:32
https://github.com/Gissio/radpro/files/14669912/radpro-bosean-fs600-2.0beta23-test7-install.bin.zip

try this, solved!

**Comment by Gissio** [comment] 2024-03-21 22:04
Duplicate of https://github.com/Gissio/radpro/issues/17.

Beta 24 is around the corner.

**Closed by Gissio** 2024-03-21 22:04 UTC
