### ISSUE TITLE
Bosean FS-600: Debugging

### ISSUE THREAD

**Issue by Dsl71** [Gissio/radpro#17] opened 2024-02-25 18:47 UTC
I tried the new 2.0 beta16 on a board revision KL7 820.403D. The display had all pixels set to black, no background light, text was only readable in a very steep angle. keyboard seems to fail also. Klicks were hearable, the LED was flashing also.

Back to 2.0beta10 everything worked again.

**Comment by Gissio** [comment] 2024-02-25 22:03
A regression, how sad. Does this work?

[radpro-bosean-fs600-2.0beta17-test1.bin.zip](https://github.com/Gissio/radpro/files/14397993/radpro-bosean-fs600-2.0beta17-test1.bin.zip)

**Comment by Dsl71** [comment] 2024-02-25 22:08
this is only 32k instead of 128k, is this okay to flash?

**Comment by Gissio** [comment] 2024-02-25 22:11
Yep. It'll complain with a checksum error because the firmware is not signed, but other than that, it should work.

**Comment by Gissio** [comment] 2024-02-25 22:12
Oh, the settings might be wrong, but you can correct them.

**Comment by Dsl71** [comment] 2024-02-26 11:40
Just flashed it. After powering, the led flashes about 5 times and then it starts with checksum error display and then it shows everything normal. Btw, first time to see an output from the random generators. Cudos to you, Gissio ;-)

**Comment by Gissio** [comment] 2024-02-26 12:34
I'm glad it works now.

Do the new display contrast/brightness settings work? Does the dead-time measurement (statistics) work? Is the battery indicator working?

**Comment by Dsl71** [comment] 2024-02-29 21:04
After about 11h runtime dead-time shows < 1.7 µs

**Comment by Dsl71** [comment] 2024-03-02 08:00
Bosean FS-600:
After about 46h runtime dead-time shows < 0.0 µs

**Comment by Gissio** [comment] 2024-03-10 16:35
I just released [2.0beta17](https://github.com/Gissio/radpro/releases). It should fix the dead-time measurement and battery level readout. Also, settings should work now.

**Comment by Dsl71** [comment] 2024-03-10 19:31
hmm, flashed it , but only the led is red all the time, no display text

**Comment by Gissio** [comment] 2024-03-11 03:50
Can you make a video and share it here?

**Comment by Dsl71** [comment] 2024-03-11 04:32
Uff, even a 5 sec video is too big. so:

- Press on
- Led lits constantly
- No screen light and text
- if  a click apears, short led off.

thats all

**Comment by Dsl71** [comment] 2024-03-11 04:48
https://github.com/Gissio/radpro/assets/57271038/a366396e-46e1-445b-8007-94acaee67f55

**Comment by Gissio** [comment] 2024-03-11 06:37
That video helped a lot, thanks! I'll keep you updated.

**Comment by Gissio** [comment] 2024-03-13 16:03
I just released Rad Pro 2.0beta18. Can you go over this checklist?

- The display/backlight works.
- Settings are stored to flash memory.
- The radiation alarms work (flashes the screen and beeps).
- While unplugged, the battery indicator works correctly.
- While plugged, the battery indicator shows a lighting icon.
- The temperature indicator in the statistics menu shows reasonable values.
- The random generator and dead-time compensation work.
- The serial port communication works.
- Data logging works and you can download it with radpro-tool.

**Comment by Dsl71** [comment] 2024-03-13 18:56
YES-  The display/backlight works.
    NO- Settings are stored to flash memory.
    The radiation alarms work (flash the screen and beep).
    YES- While unplugged, the battery indicator works correctly.
    YES- While plugged, the battery indicator shows a lighting icon.
    NO*-The temperature indicator in the statistics menu shows reasonable values.
    YES**- The random generator and dead-time compensation work.
    TBD- The serial port communication works.
    TBD- Data logging works and you can download the datalog with radpro-tool.


* Crash while entering menu,have battery to remove to reboot
** How can i check if dead-time compensation work

**Comment by Gissio** [comment] 2024-03-14 04:45
I'm sorry, I meant dead-time measurement, not dead-time compensation. If you can't enter the statistics screen, you can't do this for now.

Can you try dumping the contents of the flash memory to a file and upload it here? I'm suspecting the program code is being overwritten. This command should do the trick:

st-flash read backup.bin 0x08000000 0x20000

**Comment by Dsl71** [comment] 2024-03-14 09:25
[backup_boseanfs600_2_0_beta18.zip](https://github.com/Gissio/radpro/files/14600010/backup_boseanfs600_2_0_beta18.zip)

Here it is, its the same content than the original flash file.

**Comment by Gissio** [comment] 2024-03-14 18:53
First, thanks for your patience.

I am sending you beta19-test1.

[radpro-bosean-fs600-2.0beta19-test1-install.bin.zip](https://github.com/Gissio/radpro/files/14606811/radpro-bosean-fs600-2.0beta19-test1-install.bin.zip)

If the statistics view crashes, you should hear a series of pulses, after which the device should turn itself off. Please record these pulses using a voice recorder and attach them here to a message. They will let me know where the problem is.

Also, let me know if the settings are saved now.

**Comment by Gissio** [comment] 2024-03-14 20:15
First, thanks for your patience.

I am sending you beta19-test2.

[radpro-bosean-fs600-2.0beta19-test2-install.bin.zip](https://github.com/Gissio/radpro/files/14607495/radpro-bosean-fs600-2.0beta19-test2-install.bin.zip)

If the statistics view crashes, you should hear a series of pulses, after which the device should turn itself off. Please record these pulses using a voice recorder and attach them here to a message. They will let me know where the problem is.

Also, let me know if the settings are saved now.

**Comment by Dsl71** [comment] 2024-03-15 08:46
No Problem, thank you for your effort to bring trash counters to good counters!

Settings are not saved.

Entering the statistics screen, immediate crash, no pulses,no shutdown.

Sorry, i have no better news.

**Comment by Gissio** [comment] 2024-03-15 22:25
Beta20 (https://github.com/Gissio/radpro/releases) should fix the statistics screen crash.

**Comment by Dsl71** [comment] 2024-03-15 22:41
hmm statistics screen doesn't crash, values (temp between -7 to 125) seems to be not correct.
Settings are not saved.
deadtime shows -.-- or so.

**Comment by Gissio** [comment] 2024-03-16 02:43
I forgot to ask, does the battery indicator show the correct level of charge when unplugged?

**Comment by Dsl71** [comment] 2024-03-16 08:13
Alkaline battery, 3,9V , battery indicator shows 100% set as Ni-MH, about 30-40% set as Alkaline. But they are very weak already,have to get new ones.

**Comment by Gissio** [comment] 2024-03-16 13:21
Ok. I think I found the temperature problem: on the STM32F0x1 and STM32F1x3, temperature is read on ADC channel 18; now, on the STM32G07x, temperature is read on ADC channel 12.

So we're just left with the flash program problem. I'll keep you updated.

**Comment by Gissio** [comment] 2024-03-16 18:56
I just released beta21. The statistics view should show now the device battery voltage (per cell). Are settings preserved now?

**Comment by Dsl71** [comment] 2024-03-17 19:11
no good news for beta22 and beta23.
Battery voltage shown  around 1,5V, no settings saved.

**Comment by Gissio** [comment] 2024-03-17 20:39
Ok.

There goes beta23-test1:

[radpro-bosean-fs600-2.0beta23-test1-install.bin.zip](https://github.com/Gissio/radpro/files/14628807/radpro-bosean-fs600-2.0beta23-test1-install.bin.zip)

You should see a "FLASH_SR=" line in the status bar, followed by hexadecimal numbers.

Please turn on datalogging to 1 minute. The numbers should change. Let me know what numbers you see. Please wait for a minute. Every minute the datalog should attempt to write to flash. Do the numbers change? To what value?

Thanks.

**Comment by Dsl71** [comment] 2024-03-18 07:33
0x00000000 -> 0xc0000000 after enabling data logging of 1 minute.
0xc0000000 stays all the time (5 minutes runtime or so)

**Comment by Gissio** [comment] 2024-03-18 14:42
I think I'm onto something:

[radpro-bosean-fs600-2.0beta23-test2-install.bin.zip](https://github.com/Gissio/radpro/files/14637878/radpro-bosean-fs600-2.0beta23-test2-install.bin.zip)

Can you repeat the previous steps? And check if settings are saved now?

**Comment by Dsl71** [comment] 2024-03-18 16:16
0x00000000 -> 0x00000008 after enabling data logging of 1 minute.
0x00000008 remains all the time (5 minutes runtime or so)
Settings are not saved. After reboot, if only settings are changed value remains at 0x00000000.

FYI: I do all of this usb powered.

**Comment by Gissio** [comment] 2024-03-18 16:32
Ok, here is what is happening: the flash controller is reporting a PROGERR, which happens when attempting to write data to a memory location that was already written. I have no idea why this should occur. But at least I know what to look for.

**Comment by Dsl71** [comment] 2024-03-18 16:50
Hmm, maybe you have to erase the used sectors before writing to them?

**Comment by Gissio** [comment] 2024-03-18 18:58
Here's what I think is happening. 

The STM32G070 has flash memory with error correction, so there are invisible error bits. So, whenever a value is written to this flash memory, the error bits are also set (although they are invisible).

The Rad Pro "-install" firmware sets unused memory to 0xff, which is value of erased flash memory. Now, because of these error bits, the STM32G070 hardware detects that data has been written previously.

So, indeed, on the STM32G070 it is necessary to erase the flash memory again.

Let's try beta34-test3:



Do we agree that this is a very nasty bug?

**Comment by Gissio** [comment] 2024-03-18 19:06
Here's what I think is happening. 

The STM32G070 has flash memory with error correction, so it has invisible error bits. So, whenever a value is written to this flash memory, the error bits are also set (even though they are invisible).

The Rad Pro "-install" firmware initializes settings and datalog memory to the value of erased STM32 flash memory. But because of these error bits, the STM32G070 detects that data has been previously written (by the st-link.exe flash software), and, correctly, refuses to reflash memory.

So, indeed, it is necessary to erase the flash memory.

Let's try beta23-test3:

[radpro-bosean-fs600-2.0beta23-test3-install.bin.zip](https://github.com/Gissio/radpro/files/14641231/radpro-bosean-fs600-2.0beta23-test3-install.bin.zip)

Do we agree that this is indeed very nasty?

**Comment by Dsl71** [comment] 2024-03-18 20:00
I agree, a nasty  bug. But still no good news, settings are not saved, the FLASH_SR= line is missing too.

**Comment by Gissio** [comment] 2024-03-18 21:24
Same as before, with FLASH_SR:

[radpro-bosean-fs600-2.0beta23-test4-install.bin.zip](https://github.com/Gissio/radpro/files/14642634/radpro-bosean-fs600-2.0beta23-test4-install.bin.zip)

**Comment by Dsl71** [comment] 2024-03-19 18:56
0x00000000 -> 0x00000008 after enabling data logging of 1 minute.
0x00000008 remains all the time (5 minutes runtime or so)
Settings are not saved. After reboot, if only settings are changed, value remains at 0x00000000.

If before data logging was activated, value is now 0x00800008 when settings are changed.
Settings are not saved.

**Comment by Gissio** [comment] 2024-03-19 22:07
Odd.

Can you download the flash memory with st-link.exe read and check if there are any differences?

**Comment by Gissio** [comment] 2024-03-19 22:41
Can you try again?

[radpro-bosean-fs600-2.0beta23-test6-install.bin.zip](https://github.com/Gissio/radpro/files/14657617/radpro-bosean-fs600-2.0beta23-test6-install.bin.zip)

If it fails, can you download the flash memory with `st-link.exe read` and let me know if something changed, and how?

**Comment by Dsl71** [comment] 2024-03-20 11:47
Yippie! partly success!!! What happens:
Change settings,leave menu, power cycle -> settings are here.
Do another power cycle -> settings are default again.

**Comment by Gissio** [comment] 2024-03-20 16:46
The good news is that this is possibly due to an unrelated problem. In the STM32G070, settings were not memory aligned to 8-byte flash words. It should work now:

[radpro-bosean-fs600-2.0beta23-test7-install.bin.zip](https://github.com/Gissio/radpro/files/14669912/radpro-bosean-fs600-2.0beta23-test7-install.bin.zip)

**Comment by Dsl71** [comment] 2024-03-20 18:26
Well done Sir!

For the first time settings are safed !!!!! Cudos, Gissio

**Comment by Gissio** [comment] 2024-03-22 05:11
I'm glad it works now.

I've just released rc1 (release candidate 1). Can you check if datalogging works with the Bosean FS-600?

I've also added compatibility with GeigerLog. Does this work: https://github.com/Gissio/geigerlog-radpro ?

**Comment by Dsl71** [comment] 2024-03-22 07:23
`   flash_unlock();

    for (uint32_t i = 0; i < size; i += FLASH_WORD_SIZE)
    {
        if (!flash_program(dest + i, source + i))
        {
            if (!flash_erase_page(iterator->pageIndex))
                break;

            if (!flash_program(dest + i, source + i))
                break;
        }
    }

    flash_lock();
`

Ah i see the new flash code, looks clean and neat. I will flash rc1 and report back.

**Comment by Dsl71** [comment] 2024-03-22 08:08
Ha a first connect and data collect with geigerlog-radpro works :-)

**Comment by Dsl71** [comment] 2024-03-22 11:26
First datalogging history...
![history](https://github.com/Gissio/radpro/assets/57271038/cdba6799-8c5a-4a7f-bdeb-3e7786d2912f)

**Comment by Dsl71** [comment] 2024-03-22 12:21
![grafik](https://github.com/Gissio/radpro/assets/57271038/1314a00c-f322-486b-b9ef-cf0335ce2580)

**Comment by Dsl71** [comment] 2024-03-22 15:58
![grafik](https://github.com/Gissio/radpro/assets/57271038/fc6457ad-0636-4756-80e3-71dcd50e7612)

**Comment by Dsl71** [comment] 2024-03-22 16:33
![grafik](https://github.com/Gissio/radpro/assets/57271038/33798855-95cd-45aa-b258-aa90c3b767d2)

**Comment by Gissio** [comment] 2024-03-22 16:57
Regarding your first question: data logging stores cumulative pulse count. From there both rate and dose can be calculated.

Regarding the problem with datalogging: try the new geigerlog-radpro release. It shouldn't crash when requests don't get answered in time (there is a 250 ms timeout when the serial port is opened).

**Comment by Dsl71** [comment] 2024-03-22 17:14
Regarding: https://github.com/Gissio/radpro/issues/17#issuecomment-2014498168

I Think there should be some error handling too in the future. Otherwise you never know when a flash error occurs.

**Comment by Dsl71** [comment] 2024-03-22 17:17
![grafik](https://github.com/Gissio/radpro/assets/57271038/19e72aad-eb22-4285-a2fa-c0e258c93e12)

I am sorry. Note: data logging of 1 minute is also active.

**Comment by Gissio** [comment] 2024-03-22 22:22
Can you try geigerlog-radpro 1.4.3b?

I've changed the Rad Pro flash code once again. Now a page is only erased if writes fail at the start of the page. This improves recovery in case of an error.

**Comment by Dsl71** [comment] 2024-03-23 09:34
geigerlog-radpro 1.4.3b runs for one hour now without any problems. 

Next step: Flash the newest FW and retry...

**Comment by Dsl71** [comment] 2024-03-23 09:42
Bug, see the two timestamps...

![grafik](https://github.com/Gissio/radpro/assets/57271038/83b1346f-6d17-442b-b272-2970622133c9)

**Comment by Dsl71** [comment] 2024-03-23 09:45
Bug , from a certain point "no data", no recovery without reconnect

![grafik](https://github.com/Gissio/radpro/assets/57271038/16dcb708-0836-40c8-8766-a1e41aa2a74d)

**Comment by Dsl71** [comment] 2024-03-23 11:09
This is also very very unlikely:

![grafik](https://github.com/Gissio/radpro/assets/57271038/7336a6ab-bd16-4840-88fd-55a929cd709b)

**Comment by Dsl71** [comment] 2024-03-23 11:18
Again no data, device freezes, only pulse led is updated.

**Comment by Dsl71** [comment] 2024-03-23 15:40
![grafik](https://github.com/Gissio/radpro/assets/57271038/8a55b5bb-7ade-40b7-ab00-545ea0b35055)

I think too those peaks are related to a time base problem (missing 1 sec interrupt or so)

**Comment by Gissio** [comment] 2024-03-23 15:58
I don't like the freezing part. I will try to reproduce the problem locally (so far I had been testing with the GC-01 USB port, which seems to work quite well.

**Comment by Dsl71** [comment] 2024-03-23 16:46
FYI: at least for the CPS the poisson fit seems to be good.

![grafik](https://github.com/Gissio/radpro/assets/57271038/c4e48b90-3ebd-4cba-869a-183c729289f3)

**Comment by Dsl71** [comment] 2024-03-23 16:49
Last plot before freeze...

![grafik](https://github.com/Gissio/radpro/assets/57271038/eda34a57-9f3b-4142-99fe-40dac067dceb)

**Comment by Gissio** [comment] 2024-03-23 17:05
Taken from geigerlog-radpro's page:

    "CPM" data is Rad Pro's instantaneous counts per minute value. This value is averaged through Rad Pro's adaptive averaging algorithm.

    "CPS" data is the low-level counts per second value. This value is not averaged.

It is therefore expected that statistics on the CPM data not conform to the Poisson distribution.

This should probably be stated in the radpro docs as well. Thanks for pointing this out.

**Comment by Gissio** [comment] 2024-03-25 19:10
Can you try again?

[radpro-bosean-fs600-2.0rc2-test1-install.bin.zip](https://github.com/Gissio/radpro/files/14748399/radpro-bosean-fs600-2.0rc2-test1-install.bin.zip)

Fixed a race condition and an error condition (involving the "ORE" flag) that led to interrupts being generated continuously.

**Comment by Dsl71** [comment] 2024-03-26 07:42
Device freezes at connection attempt..

![grafik](https://github.com/Gissio/radpro/assets/57271038/ac9b7dde-9923-4f44-ab67-5124410d601b)

**Comment by Gissio** [comment] 2024-03-26 14:53
STM32G070 madness again... And now?

[radpro-bosean-fs600-2.0rc2-test2-install.bin.zip](https://github.com/Gissio/radpro/files/14760314/radpro-bosean-fs600-2.0rc2-test2-install.bin.zip)

With [GeigerLog 1.4.3c](https://github.com/Gissio/geigerlog-radpro)?

**Comment by Gissio** [comment] 2024-03-26 16:33
Ohje.

By the way, please tell the people in the other forum that the KL7 820.403A has the pulse LED wired directly to the pulse detection circuit. Thus it can't be disabled by software.

The KL7 820.403D has the pulse LED wired to the MCU, so it is possible to disable the pulse LED by software.

In order to keep things simple, I decided to use the same firmware for both board revisions.

**Comment by Dsl71** [comment] 2024-03-30 20:54
Ah,yes, a new topic is welcome. btw happy easter...

**Comment by Dsl71** [comment] 2024-04-06 22:36
Meanwhile i got a second Bosean FS-600. Should i send it to you for debugging purposes?

**Comment by Gissio** [comment] 2024-04-07 18:30
Your offer is greatly appreciated!

But I don't think it is necessary. It's just that I'm just out of time these days. I don't think it will be hard to fix the serial port problem.

**Comment by Gissio** [comment] 2024-04-19 17:40
I finally found the time to work on this. Here goes 2.0rc3test4 for FS-600:

[radpro-bosean-fs600-2.0rc3-test4.bin.zip](https://github.com/Gissio/radpro/files/15043885/radpro-bosean-fs600-2.0rc3-test4.bin.zip)

**Comment by Dsl71** [comment] 2024-04-19 22:08
Same as before, User Interface freeze, GeigerLog does not recognize device. BTW nice bargraph, instantaneous values not correct. ( 3-7 µSV/h if an impulse comes in, then -.--- if no impulse comes in shortly afterwards.) Persistent settings are safed still.

**Comment by Dsl71** [comment] 2024-04-19 22:10
Average 4 µSv/h...

**Comment by Gissio** [comment] 2024-04-20 21:50
I found the communications bug! It was a silly "set" that should have been a "get".

I also fixed the instantaneous rate error, which slipped in in the last minute.

There goes 2.0rc6, packaged with the brand-new `radpro-flashtool`. Just start the `flash-bosean-fs600.bat` file.

[radpro-flashtool-2.0rc6.zip](https://github.com/Gissio/radpro/files/15049832/radpro-flashtool-2.0rc6.zip)

**Comment by Dsl71** [comment] 2024-04-21 00:00
hmm it says syntax error and there is no bin file in the zip

**Comment by Gissio** [comment] 2024-04-21 00:27
Can you try again?

[radpro-flashtool-2.0rc3-test6.zip](https://github.com/Gissio/radpro/files/15050230/radpro-flashtool-2.0rc3-test6.zip)

**Comment by Dsl71** [comment] 2024-04-21 01:18
10 Pro 21H2. Flashing worked now..

**Comment by Dsl71** [comment] 2024-04-21 01:24
AAAANNNNNDDDD... Geigerlog not freezing device hehe

**Comment by Dsl71** [comment] 2024-04-21 02:11
![grafik](https://github.com/Gissio/radpro/assets/57271038/12eeafad-28e8-4ba1-9723-832d232f10ed)
Later more, now is 4AM here hehe

**Comment by Gissio** [comment] 2024-04-21 04:51
BTW, did you check the display when an alarm goes off?

**Comment by Dsl71** [comment] 2024-04-21 11:32
Now i did. Wow nice flashing.

**Comment by Gissio** [comment] 2024-04-21 16:18
Can we celebrate by closing this issue?

**Comment by Dsl71** [comment] 2024-04-21 16:43
Yes, wi should close, really great work. BTW flashing the FS 2011 with the new tool didn't work. I used the old method:

st-flash.exe write radpro-fs2011-gd32f150c8-2.0rc3-image.bin 0x08000000

**Comment by Gissio** [comment] 2024-04-21 17:16
Can you post the `flashtool` messages log?

**Comment by Dsl71** [comment] 2024-04-21 18:46
uff, at the next release, just closed the GC.

**Comment by Dsl71** [comment] 2024-04-21 18:46
And under a new Topic...

**Comment by Gissio** [comment] 2024-04-21 19:06
Please don't forget. Closing this thread.

**Closed by Gissio** 2024-04-21 19:06 UTC
Labels: bug

**Comment by Gissio** [comment] 2024-04-27 18:50
> Now i did. Wow nice flashing. And the speed of the instantaneous, if you remove hotter sources... super

Is it too much to ask if you could make a video and upload it to YouTube, showcasing the features of Rad Pro?
